#!/usr/bin/env python

import xml.etree.ElementTree as xml
import commands
from bzrlib.branch import BzrBranch


print commands.getoutput("./update_translations.py")

version = open("VERSION").readline().strip()


branch = BzrBranch.open(".")
revno = branch.revno()
revno += 1
revno = str(revno)


glade_file = "share/caffeine/glade/GUI.glade"

tree = xml.parse(glade_file)

rootElement = tree.getroot()

for elem in rootElement:
    
    if elem.get("id") == "aboutdialog":

        for child in elem:
            if child.get("name") == "version":

                child.text = version+" (bzr "+revno+")"


tree.write(glade_file)

