#!/bin/sh

gtk-update-icon-cache /usr/share/icons/hicolor
gtk-update-icon-cache /usr/share/icons/ubuntu-mono-light
gtk-update-icon-cache /usr/share/icons/ubuntu-mono-dark

glib-compile-schemas /usr/share/glib-2.0/schemas

exit 0
